In [1]:
import warnings # ln 25 was creating warnings
warnings.filterwarnings('ignore')

In [2]:
%matplotlib inline
from matplotlib import pyplot as plt
from sklearn.datasets import load_digits
import pandas as pd
import numpy as np

In [3]:
digits = load_digits()
dir(digits)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target) # (flattened 2d array,1d array)

__Logistic Regression__

In [5]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
lr.fit(X_train,y_train)

LogisticRegression()

In [6]:
lr.score(X_test,y_test)

0.9688888888888889

__Support Vector Machines__

In [7]:
from sklearn.svm import SVC
svm = SVC()
svm.fit(X_train,y_train)

SVC()

In [8]:
svm.score(X_test,y_test)

0.9822222222222222

__Randomforest__ 

In [9]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=50) #default no of trees is 100 ('n_estimators': 100). Observe next cell o/p
rf.fit(X_train,y_train)

RandomForestClassifier(n_estimators=50)

In [10]:
rf.score(X_test,y_test)

0.9666666666666667

__Now predicting scores using kfold cross validation:__

We will use sklearns kfold to generate indices for train test splitting. Below is the trial.

In [11]:
from sklearn.model_selection import KFold
kf = KFold(n_splits= 3) # default n_splits = 5
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [12]:
for i,j in kf.split([11,12,13,14,15,16,17,18,19,20]):  # generates the indices for train and test set
    print(i,j)

[4 5 6 7 8 9] [0 1 2 3]
[0 1 2 3 7 8 9] [4 5 6]
[0 1 2 3 4 5 6] [7 8 9]


In [13]:
from sklearn.model_selection import StratifiedKFold # just another way to split 
skf = StratifiedKFold(n_splits= 3) # default n_splits = 5
skf

StratifiedKFold(n_splits=3, random_state=None, shuffle=False)

__Train test split based on indices with kfold technique and finding the scores for each model__

In [14]:
scores_lr = []
scores_svm = []
scores_rf= []

In [15]:
from sklearn.model_selection import KFold
kf = KFold(n_splits= 3) # default n_splits = 5
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [16]:
#trial
for i,j in kf.split(digits.data): #Iterates for n_splits= 3 ad returns the indices.Refer next cell for implementation.
    print (i.shape) #returns indices for train set
    print (j.shape) #returns indices for test set

(1198,)
(599,)
(1198,)
(599,)
(1198,)
(599,)


In [17]:
for i,j in kf.split(digits.data): #Iterates for n_splits= 3 ad returns the indices.Refer next cell for implementation.
    X_train, X_test, y_train, y_test= digits.data[i],digits.data[j],digits.target[j],digits.target[j]
    scores_lr.append(lr.score(X_test,y_test))
    scores_svm.append(svm.score(X_test,y_test))
    scores_rf.append(rf.score(X_test,y_test))

In [18]:
scores_lr

[0.994991652754591, 0.994991652754591, 0.986644407345576]

In [19]:
scores_svm

[0.994991652754591, 0.996661101836394, 0.986644407345576]

In [20]:
scores_rf

[0.994991652754591, 0.993322203672788, 0.986644407345576]

In [21]:
np.mean(np.asarray(scores_lr)) #as array converts list to array. can also use pythons sum(list)/len(list) to find mean

0.9922092376182526

In [22]:
np.mean(np.asarray(scores_svm))

0.9927657206455204

In [23]:
np.mean(np.asarray(scores_rf))

0.991652754590985

__Using sklearns cross validation to split and find the score__

In [24]:
from sklearn.model_selection import cross_val_score  #default n_splits = 5

In [25]:
cross_val_score(lr,digits.data,digits.target) #takes (estimator,X,y) # warnings disabled first cell.

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [26]:
cross_val_score(svm,digits.data,digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [27]:
cross_val_score(rf,digits.data,digits.target)

array([0.92777778, 0.88611111, 0.9637883 , 0.96657382, 0.92479109])

In [28]:
np.mean(cross_val_score(lr,digits.data,digits.target)) #taking mean of above scores

0.9137650882079852

In [29]:
np.mean(cross_val_score(svm,digits.data,digits.target))

0.9632838130609718

In [30]:
np.mean(cross_val_score(rf,digits.data,digits.target))

0.937700402352213

__Parameter tuning can also be done using cross_validation__

    Consider for random forest we can adjust the n_estimator(i.e. decision trees)

In [34]:
# cross_val_score(RandomForestClassifier(n_estimators=10),digits.data,digits.target)
cross_val_score(RandomForestClassifier(n_estimators=10),digits.data,digits.target,cv =3) # cv=3 will return only 3 scores 

array([0.88647746, 0.91318865, 0.88814691])

In [35]:
cross_val_score(RandomForestClassifier(n_estimators=50),digits.data,digits.target)

array([0.93611111, 0.91111111, 0.94986072, 0.9637883 , 0.93593315])

In [36]:
cross_val_score(RandomForestClassifier(n_estimators=100),digits.data,digits.target)

array([0.92222222, 0.91944444, 0.95543175, 0.9637883 , 0.92200557])