In [1]:
import warnings # ln 25 was creating warnings
warnings.filterwarnings('ignore')

In [16]:
%matplotlib inline
from matplotlib import pyplot as plt
from sklearn.datasets import load_iris
import pandas as pd
import numpy as np

In [3]:
iris = load_iris()
dir(iris)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

__Scores of all algorithms (using simple train_test_split)__

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target) # (flattened 2d array,1d array)

In [5]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
lr.fit(X_train,y_train)

LogisticRegression()

In [6]:
lr.score(X_test,y_test)

1.0

In [7]:
from sklearn.svm import SVC
svm = SVC()
svm.fit(X_train,y_train)

SVC()

In [8]:
svm.score(X_test,y_test)

0.9736842105263158

In [9]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=50) #default no of trees is 100 ('n_estimators': 100). Observe next cell o/p
rf.fit(X_train,y_train)

RandomForestClassifier(n_estimators=50)

In [10]:
rf.score(X_test,y_test)

0.9736842105263158

__Scores of all algorithms (using cross validation)__

In [11]:
from sklearn.model_selection import cross_val_score  

In [13]:
#default cv=5 in cross_val_score
cross_val_score(lr,iris.data,iris.target,cv=3) #takes (estimator,X,y) # warnings disabled first cell.

array([0.98, 0.96, 0.98])

In [14]:
cross_val_score(svm,iris.data,iris.target,cv=3) #takes (estimator,X,y) # warnings disabled first cell.

array([0.96, 0.98, 0.94])

In [15]:
cross_val_score(rf,iris.data,iris.target,cv=3) #takes (estimator,X,y) # warnings disabled first cell.

array([0.98, 0.94, 0.96])