__Note: Scaling the features before applying PCA is the most important Task.__
    
     1. Percentage retention: percentage of features to preserve 
     2. Component retention: n_components selection (based on the order of their contribution)

In [1]:
%matplotlib inline
from matplotlib import pyplot as plt
from sklearn.datasets import load_digits
import pandas as pd
import numpy as np

In [2]:
digits = load_digits()
dir(digits)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

In [3]:
digits.feature_names[:5] #checking the column names

['pixel_0_0', 'pixel_0_1', 'pixel_0_2', 'pixel_0_3', 'pixel_0_4']

In [4]:
df = pd.DataFrame(digits.data, columns = digits.feature_names)
df

pixel_0_0  pixel_0_1  pixel_0_2  pixel_0_3  pixel_0_4  pixel_0_5  \
0           0.0        0.0        5.0       13.0        9.0        1.0   
1           0.0        0.0        0.0       12.0       13.0        5.0   
2           0.0        0.0        0.0        4.0       15.0       12.0   
3           0.0        0.0        7.0       15.0       13.0        1.0   
4           0.0        0.0        0.0        1.0       11.0        0.0   
...         ...        ...        ...        ...        ...        ...   
1792        0.0        0.0        4.0       10.0       13.0        6.0   
1793        0.0        0.0        6.0       16.0       13.0       11.0   
1794        0.0        0.0        1.0       11.0       15.0        1.0   
1795        0.0        0.0        2.0       10.0        7.0        0.0   
1796        0.0        0.0       10.0       14.0        8.0        1.0   

      pixel_0_6  pixel_0_7  pixel_1_0  pixel_1_1  ...  pixel_6_6  pixel_6_7  \
0           0.0        0.0        0.0        0.0  ...        0.0        0.0   
1           0.0        0.0        0.0        0.0  ...        0.0        0.0   
2           0.0        0.0        0.0        0.0  ...        5.0        0.0   
3           0.0        0.0        0.0        8.0  ...        9.0        0.0   
4           0.0        0.0        0.0        0.0  ...        0.0        0.0   
...         ...        ...        ...        ...  ...        ...        ...   
1792        0.0        0.0        0.0        1.0  ...        4.0        0.0   
1793        1.0        0.0        0.0        0.0  ...        1.0        0.0   
1794        0.0        0.0        0.0        0.0  ...        0.0        0.0   
1795        0.0        0.0        0.0        0.0  ...        2.0        0.0   
1796        0.0        0.0        0.0        2.0  ...        8.0        0.0   

      pixel_7_0  pixel_7_1  pixel_7_2  pixel_7_3  pixel_7_4  pixel_7_5  \
0           0.0        0.0        6.0       13.0       10.0        0.0   
1           0.0        0.0        0.0       11.0       16.0       10.0   
2           0.0        0.0        0.0        3.0       11.0       16.0   
3           0.0        0.0        7.0       13.0       13.0        9.0   
4           0.0        0.0        0.0        2.0       16.0        4.0   
...         ...        ...        ...        ...        ...        ...   
1792        0.0        0.0        2.0       14.0       15.0        9.0   
1793        0.0        0.0        6.0       16.0       14.0        6.0   
1794        0.0        0.0        2.0        9.0       13.0        6.0   
1795        0.0        0.0        5.0       12.0       16.0       12.0   
1796        0.0        1.0        8.0       12.0       14.0       12.0   

      pixel_7_6  pixel_7_7  
0           0.0        0.0  
1           0.0        0.0  
2           9.0        0.0  
3           0.0        0.0  
4           0.0        0.0  
...         ...        ...  
1792        0.0        0.0  
1793        0.0        0.0  
1794        0.0        0.0  
1795        0.0        0.0  
1796        1.0        0.0  

[1797 rows x 64 columns]

__Data Exploration__

In [5]:
df.describe() #observe min and max is between 0-16 for every pixel.

pixel_0_0    pixel_0_1    pixel_0_2    pixel_0_3    pixel_0_4  \
count     1797.0  1797.000000  1797.000000  1797.000000  1797.000000   
mean         0.0     0.303840     5.204786    11.835838    11.848080   
std          0.0     0.907192     4.754826     4.248842     4.287388   
min          0.0     0.000000     0.000000     0.000000     0.000000   
25%          0.0     0.000000     1.000000    10.000000    10.000000   
50%          0.0     0.000000     4.000000    13.000000    13.000000   
75%          0.0     0.000000     9.000000    15.000000    15.000000   
max          0.0     8.000000    16.000000    16.000000    16.000000   

         pixel_0_5    pixel_0_6    pixel_0_7    pixel_1_0    pixel_1_1  ...  \
count  1797.000000  1797.000000  1797.000000  1797.000000  1797.000000  ...   
mean      5.781859     1.362270     0.129661     0.005565     1.993879  ...   
std       5.666418     3.325775     1.037383     0.094222     3.196160  ...   
min       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
25%       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
50%       4.000000     0.000000     0.000000     0.000000     0.000000  ...   
75%      11.000000     0.000000     0.000000     0.000000     3.000000  ...   
max      16.000000    16.000000    15.000000     2.000000    16.000000  ...   

         pixel_6_6    pixel_6_7    pixel_7_0    pixel_7_1    pixel_7_2  \
count  1797.000000  1797.000000  1797.000000  1797.000000  1797.000000   
mean      3.725097     0.206455     0.000556     0.279354     5.557596   
std       4.919406     0.984401     0.023590     0.934302     5.103019   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.000000     0.000000     0.000000     0.000000     1.000000   
50%       1.000000     0.000000     0.000000     0.000000     4.000000   
75%       7.000000     0.000000     0.000000     0.000000    10.000000   
max      16.000000    13.000000     1.000000     9.000000    16.000000   

         pixel_7_3    pixel_7_4    pixel_7_5    pixel_7_6    pixel_7_7  
count  1797.000000  1797.000000  1797.000000  1797.000000  1797.000000  
mean     12.089037    11.809126     6.764051     2.067891     0.364496  
std       4.374694     4.933947     5.900623     4.090548     1.860122  
min       0.000000     0.000000     0.000000     0.000000     0.000000  
25%      11.000000    10.000000     0.000000     0.000000     0.000000  
50%      13.000000    14.000000     6.000000     0.000000     0.000000  
75%      16.000000    16.000000    12.000000     2.000000     0.000000  
max      16.000000    16.000000    16.000000    16.000000    16.000000  

[8 rows x 64 columns]

In [6]:
df.describe().loc['max'].value_counts().sort_index(ascending = False) 

16.0    43
15.0     3
14.0     2
13.0     1
12.0     1
9.0      1
8.0      3
6.0      1
4.0      1
2.0      2
1.0      3
0.0      3
Name: max, dtype: int64

In [7]:
X = df
y = digits.target

__Using Standard scaler__ 
    
    Scaling is the most important part of Principal component analysis. 
    Min-Max scaler can also be used.

In [8]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
X_scaled

array([[ 0.        , -0.33501649, -0.04308102, ..., -1.14664746,
        -0.5056698 , -0.19600752],
       [ 0.        , -0.33501649, -1.09493684, ...,  0.54856067,
        -0.5056698 , -0.19600752],
       [ 0.        , -0.33501649, -1.09493684, ...,  1.56568555,
         1.6951369 , -0.19600752],
       ...,
       [ 0.        , -0.33501649, -0.88456568, ..., -0.12952258,
        -0.5056698 , -0.19600752],
       [ 0.        , -0.33501649, -0.67419451, ...,  0.8876023 ,
        -0.5056698 , -0.19600752],
       [ 0.        , -0.33501649,  1.00877481, ...,  0.8876023 ,
        -0.26113572, -0.19600752]])

In [9]:
np.min(X_scaled) #minimum value from the whole numpy array after scaling

-3.0125999462748765

In [10]:
np.max(X_scaled[0]) #max value from the whole numpy array after scaling.

1.905963466976408

__Train test Split__

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_scaled,digits.target,test_size=0.2,random_state=2)

In [12]:
len(X_train), len(X_test), len(y_train), len(y_test)

(1437, 360, 1437, 360)

__Logistic Regression__

In [13]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(max_iter=1000)
model.fit(X_train,y_train)
model.score(X_test,y_test)

0.95

## __PCA (PRINCIPAL COMPONENT ANALYSIS)__

__METHOD1 : Percentage retention__

Reduces the features while retaining x% of valuable info. 

In [14]:
from sklearn.decomposition import PCA 
pca1 = PCA(0.95)
X_pca1 = pca1.fit_transform(X_scaled)
X_pca1.shape  

(1797, 40)

In [15]:
X.shape

(1797, 64)

In [16]:
X_pca1[0].shape

(40,)

In [17]:
pca1.explained_variance_ratio_ # explains the variance (1st column preserve 14 %, 2nd col preserved 13 % of info etc)

array([0.12033916, 0.09561054, 0.08444415, 0.06498408, 0.04860155,
       0.0421412 , 0.03942083, 0.03389381, 0.02998221, 0.02932003,
       0.02781805, 0.02577055, 0.02275303, 0.0222718 , 0.02165229,
       0.01914167, 0.01775547, 0.01638069, 0.0159646 , 0.01489191,
       0.0134797 , 0.01271931, 0.01165837, 0.01057647, 0.00975316,
       0.00944559, 0.00863014, 0.00836643, 0.00797693, 0.00746471,
       0.00725582, 0.00691911, 0.00653909, 0.00640793, 0.00591384,
       0.00571162, 0.00523637, 0.00481808, 0.00453719, 0.00423163])

In [18]:
pca1.n_components_ #count of the new generated columns

40

In [19]:
pca1.n_components # percentage preservation as we mentioned in the input.

0.95

__Traintest splitting__

In [20]:
from sklearn.model_selection import train_test_split
X_train_pca, X_test_pca, y_train, y_test = train_test_split(X_pca1,digits.target,test_size=0.2,random_state = 2)

In [21]:
X_train_pca.shape, X_test_pca.shape, y_train.shape, y_test.shape

((1437, 40), (360, 40), (1437,), (360,))

__Logistic Regression__

In [22]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(max_iter=1000) # convergence error was throwing without n_iter.Grad desc was failing to converge.
model.fit(X_train_pca,y_train)
model.score(X_test_pca,y_test)

0.9416666666666667

__Method 2: Component Retention__

Reduces to (n_components = x) features

In [26]:
from sklearn.decomposition import PCA 
pca2 = PCA(n_components=2)
X_pca2 = pca2.fit_transform(X_scaled)
X_pca2.shape 

(1797, 2)

In [27]:
pca2.explained_variance_ratio_ 

array([0.12033916, 0.09561054])

In [28]:
from sklearn.model_selection import train_test_split
X_train_pca, X_test_pca, y_train, y_test = train_test_split(X_pca2,digits.target,test_size=0.2,random_state = 2)

In [29]:
X_train_pca.shape, X_test_pca.shape, y_train.shape, y_test.shape

((1437, 2), (360, 2), (1437,), (360,))

In [30]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(max_iter=1000) # convergence error was throwing without n_iter.Grad desc was failing to converge.
model.fit(X_train_pca,y_train)
model.score(X_test_pca,y_test)

0.5416666666666666

__We see that as the features are dropped to a very low number (i.e 2 here) the compuational speed increases but  we do not get a good amount of accuracy.__